language: node_js
node_js:
  - 10.16.3
branches:
  only:
    - master
before_script:
  - npm install firebase-tools -g
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
  - firebase deploy --only hosting --token "1//03NSgdZCdlWDHCgYIARAAGAMSNwF-L9IrravzB06_OQJAnYVSjCVM4cuB7ajxt8o_QbddZlWWDwbsbTW4wf6dLDVet_4cK9G5FlY"
